using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EulerProblem2
{
    class Program
    {
        //Each new term in the Fibonacci sequence is generated by adding the previous two
        //terms. By starting with 1 and 2, the first 10 terms will be:

        //1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

        //By considering the terms in the Fibonacci sequence whose values do not exceed
        //four million, find the sum of the even-valued terms.

        static void Main(string[] args)
        {
            Console.WriteLine(FibEvenSum(2, 1, new int?(2), 4000000).Value.ToString());
            Console.ReadLine();
        }

        static int? FibEvenSum(int nMinus1, int nMinus2, int? sum, int max)
        {
            int n = nMinus1 + nMinus2;

            if (n > max)
                return sum;

            if (n % 2 == 0)
                sum += n;

            return FibEvenSum(n, nMinus1, sum, max);
        }
    }
}
